name: skysporttwonz

on:
  workflow_dispatch:

jobs:
  skysporttwonz:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Install ffmpeg 
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{ secrets.CRICKET_PORTAL_URL }}/bash/skysporttwonz.sh || echo "Primary URL download failed"
        
      - name: Check if bash file exists and download from backup if not
        run: |
          if [ ! -f skysporttwonz.sh ]; then
            echo "Primary URL file not found, downloading from backup URL"
            wget ${{ secrets.CRICKET_BACKUP_BASH_URL }}/skysporttwonz.sh
          else
            echo "Bash file downloaded successfully"
          fi


      - name: Install dos2unix
        run: sudo apt install dos2unix -y
        
      - name: Install Git
        run: sudo apt install git -y
        
      - name: Install torsocks
        run: sudo apt install torsocks git -y
                
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y

      - name: Install inotifywait
        run: sudo apt install inotify-tools -y
        
      - name: Install curl
        run: sudo apt install curl -y
        
      - name: Add NodeJS
        run: curl -s https://deb.nodesource.com/setup_18.x | sudo bash
        
      - name: Install NodeJS
        run: sudo apt install nodejs -y
        
      - name: Install Wrangler
        run: npm install wrangler@latest

      - name: Fix issue in downloaded file
        run: sudo dos2unix skysporttwonz.sh
        
      - name: Permission to downloaded file
        run: sudo chmod +x skysporttwonz.sh

      - name: Permission to downloaded file
        run: sudo chmod 777 skysporttwonz.sh
        
      - name: Run the downloaded bash file
        run: sudo bash skysporttwonz.sh
  trigger_workflow:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Sleep for 5 hours and 58 minutes
        run: sleep $((5*3600 + 58*60))
      - name: Trigger new workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/skysporttwonz.yml/dispatches \
            -d '{"ref":"main"}'
